name: ManyHats
version: '${project.version}'
main: dev.nixii.manyhats.ManyHats
api-version: '1.21'

depend: [ManPage]

commands:
  hat:
    description: Swap your helmet and held item.
    usage: /<command>
    permission: manyhats.hat
permissions:
  manyhats.hat:
    description: Allow people to use the hat command
    default: true